version: '3.8'
services:
  # rabbitmq:
  #   image: rabbitmq:3.8-management
  #   networks:
  #     - app-network
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  # stock-service:
  #   image: deliverymuch/backend-challenge:stock-service
  #   networks:
  #     - app-network
  #   environment:
  #     - RABBITMQ_URL=amqp://rabbitmq
  #   depends_on:
  #     - rabbitmq
  #   links:
  #     - rabbitmq
  #   restart: on-failure
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2021!
    ports:
      - '27017:27017'
    networks:
      - mongo-compose-network

networks:
  # app-network:
  #   driver: bridge
  mongo-compose-network:
    driver: bridge
